/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * JSON Placeholder API
 * See https://jsonplaceholder.typicode.com/
 * OpenAPI spec version: 1.0.0
 */

export interface Post {
  completed: string;
  id: number;
  title: string;
  userId: number;
}
